#!/usr/bin/env -S bash -v
set -e

QUARTO_VERSION=1.7.29

echo "Installing Quarto ${QUARTO_VERSION}"
curl -LO "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
dpkg -x "quarto-${QUARTO_VERSION}-linux-amd64.deb" .quarto
rm -f "quarto-${QUARTO_VERSION}-linux-amd64.deb"
mkdir -p ~/.local/bin
ln -sf ~/.quarto/opt/quarto/bin/quarto ~/.local/bin/quarto
ln -sf ~/.quarto/opt/quarto/bin/tools/x86_64/pandoc ~/.quarto/opt/quarto/bin/tools/pandoc

echo "Completed postBuild"
